Repository patroni/patroni, pull requests merged in 2023-03, with the labels that each got.

#2579 Compatibility with flake8>=5.0
  setup.py
Labels: ci

#2576 add "GET /metrics" rest_api.rst
  docs/rest_api.rst
Labels: documentation

#2578 Don't allow on_reload callback kill other callbacks
  patroni/ha.py
  patroni/postgresql/__init__.py
  patroni/postgresql/callback_executor.py
  tests/test_callback_executor.py
  tests/test_postgresql.py
Labels: bug

#2583 Don't write to PGDATA if major version is not known
  patroni/postgresql/__init__.py
  patroni/postgresql/misc.py
  tests/test_bootstrap.py
  tests/test_ha.py
  tests/test_postgresql.py
Labels: bug

#2585 Make K8s retriable HTTP status code configurable
  docs/ENVIRONMENT.rst
  docs/SETTINGS.rst
  patroni/config.py
  patroni/dcs/kubernetes.py
  patroni/validator.py
  tests/test_config.py
  tests/test_kubernetes.py
  tests/test_validator.py
Labels: new feature

#2597 Fix bug with metadata after coordinator failover
  features/citus.feature
  features/steps/citus.py
  patroni/postgresql/citus.py
Labels: bug

#2590 Use IMDSv2 in aws callback example script
  patroni/scripts/aws.py
  tests/test_aws.py
Labels: enhancement

#2571 Remove python 2.7 support
  features/environment.py
  patroni/api.py
  patroni/config.py
  patroni/ctl.py
  patroni/daemon.py
  patroni/dcs/__init__.py
  patroni/dcs/consul.py
  patroni/dcs/etcd.py
  patroni/dcs/etcd3.py
  patroni/dcs/exhibitor.py
  patroni/dcs/kubernetes.py
  patroni/dcs/zookeeper.py
  patroni/ha.py
  patroni/log.py
  patroni/postgresql/__init__.py
  patroni/postgresql/bootstrap.py
  patroni/postgresql/citus.py
  patroni/postgresql/config.py
  patroni/postgresql/rewind.py
  patroni/postgresql/validator.py
  patroni/request.py
  patroni/utils.py
  patroni/validator.py
  patroni/watchdog/base.py
  requirements.txt
  tests/test_api.py
  tests/test_config.py
  tests/test_ctl.py
  tests/test_ha.py
  tests/test_kubernetes.py
  tests/test_log.py
  tests/test_patroni.py
  tests/test_postgresql.py
  tests/test_postmaster.py
  tests/test_rewind.py
  tests/test_utils.py
  tests/test_validator.py
  tests/test_wale_restore.py
  tests/test_zookeeper.py
Labels: refactoring

#2598 high availability across multiple datacenter #2587
  docs/_static/multi-dc-asynchronous-replication.drawio
  docs/_static/multi-dc-asynchronous-replication.png
  docs/_static/multi-dc-synchronous-replication.drawio
  docs/_static/multi-dc-synchronous-replication.png
  docs/ha_multi_dc.rst
  docs/index.rst
Labels: documentation

#2611 Add docstrings to `patroni/version.py`
  patroni/version.py
Labels: codestyle

#2614 Make sure Cluster.sync is never empty
  patroni/dcs/__init__.py
  patroni/dcs/consul.py
  patroni/dcs/etcd.py
  patroni/dcs/raft.py
  patroni/ha.py
  tests/test_ha.py
  tests/test_slots.py
Labels: bug, enhancement

#2615 Add metric to report about sync standby replica status, see #2613
  docs/rest_api.rst
  patroni/api.py
  tests/test_api.py
Labels: enhancement

#2610 Add docstrings and type annotations to `patroni/daemon.py`
  patroni/daemon.py
Labels: refactoring, codestyle

#2619 Improve behaviour of SyncState.matches()
  patroni/api.py
  patroni/dcs/__init__.py
  patroni/ha.py
  patroni/postgresql/sync.py
  patroni/utils.py
  tests/test_api.py
Labels: enhancement

#2612 Add docstrings and type annotations to `patroni/validator.py`
  patroni/validator.py
Labels: refactoring, codestyle

#2624 Add docstrings and type annotations to `patroni/utils.py`
  patroni/utils.py
Labels: codestyle
