Repository patroni/patroni, pull requests merged in 2023-12, with the labels that each got.

#2970 Don't let replica restore initialize key when DCS was wiped
  patroni/ha.py
  tests/test_ha.py
Labels: bug

#2976 Disable SSL for MacOS GH action runners
  features/environment.py
Labels: ci

#2974 Use consistent read when fetching just updated sync key
  patroni/dcs/consul.py
Labels: bug

#2975 Reload postgres config if a server param was reset
  patroni/postgresql/config.py
  patroni/utils.py
  tests/__init__.py
  tests/test_postgresql.py
Labels: bug

#2986 Update PG version in a couple of places
  .github/workflows/install_deps.py
  .github/workflows/mapping.py
  .github/workflows/run_tests.py
  .github/workflows/tests.yaml
  Dockerfile
  Dockerfile.citus
  kubernetes/Dockerfile
  kubernetes/Dockerfile.citus
  patroni/postgresql/postmaster.py
Labels: ci

#2983 Exclude leader from failover candidates in ctl
  patroni/ctl.py
  tests/test_ctl.py
Labels: bug

#2989 Implement validation of the `log` section
  patroni/validator.py
  tests/test_validator.py
Labels: enhancement

#2950 Abstract CitusHandler and decouple it from configuration
  patroni/__main__.py
  patroni/api.py
  patroni/ctl.py
  patroni/dcs/__init__.py
  patroni/dcs/consul.py
  patroni/dcs/etcd.py
  patroni/dcs/etcd3.py
  patroni/dcs/exhibitor.py
  patroni/dcs/kubernetes.py
  patroni/dcs/raft.py
  patroni/dcs/zookeeper.py
  patroni/ha.py
  patroni/postgresql/__init__.py
  patroni/postgresql/mpp/__init__.py
  patroni/postgresql/mpp/citus.py
  patroni/postgresql/slots.py
  tests/__init__.py
  tests/test_citus.py
  tests/test_consul.py
  tests/test_ctl.py
  tests/test_etcd.py
  tests/test_etcd3.py
  tests/test_exhibitor.py
  tests/test_ha.py
  tests/test_kubernetes.py
  tests/test_mpp.py
  tests/test_raft.py
  tests/test_zookeeper.py
Labels: refactoring

#2990 Create citus database and extension idempotently
  patroni/postgresql/mpp/citus.py
Labels: enhancement, citus

#2994 CREATE DATABASE cannot be executed from a function
  patroni/postgresql/mpp/citus.py
  patroni/psycopg.py
  tests/__init__.py
  tests/test_citus.py
Labels: bug
