Repository patroni/patroni, pull requests merged in 2023-10, with the labels that each got.

#2874 Add a documentation page for `patronictl`
  docs/ENVIRONMENT.rst
  docs/citus.rst
  docs/dcs_failsafe_mode.rst
  docs/dynamic_configuration.rst
  docs/existing_data.rst
  docs/index.rst
  docs/patroni_configuration.rst
  docs/patronictl.rst
  docs/pause.rst
  docs/replica_bootstrap.rst
  docs/rest_api.rst
  docs/security.rst
  docs/yaml_configuration.rst
Labels: documentation

#2869 Enforce loop_wait/retry_timeout/ttl rule
  docs/dynamic_configuration.rst
  patroni/config.py
  tests/test_config.py
Labels: enhancement

#2896 Ignore synchronous_mode setting in a standby cluster
  features/standby_cluster.feature
  features/steps/standby_cluster.py
  patroni/config.py
  tests/test_config.py
Labels: bug

#2895 Take IP from the pod if `kubernetes.pod_ip` is missing
  patroni/dcs/kubernetes.py
  tests/test_kubernetes.py
Labels: bug

#2900 Bugfix: standby cluster switchover
  patroni/dcs/zookeeper.py
  patroni/ha.py
Labels: bug, ci

#2899 Change cb checks in standby cluster behave test
  features/standby_cluster.feature
Labels: ci

#2901 Refine the documentation about custom_conf
  docs/patroni_configuration.rst
Labels: documentation

#2905 %s/iter_dcs_modules/iter_dcs_classes/g
  patroni/dcs/__init__.py
Labels: typo, codestyle

#2902 Make it easier to debug callbacks
  features/environment.py
  patroni/postgresql/callback_executor.py
Labels: enhancement, ci

#2903 Set citus.local_hostname
  docs/citus.rst
  patroni/postgresql/citus.py
  tests/__init__.py
  tests/test_bootstrap.py
  tests/test_citus.py
Labels: bug, enhancement

#2912 Update README.md to reflect changes in etcd v3
  docker/README.md
Labels: documentation

#2914 Enable Citus behave tests for Postgres v16
  .github/workflows/install_deps.py
  features/citus.feature
  features/steps/citus.py
Labels: ci

#2909 Don't cache anything in Zookeeper implementation
  features/environment.py
  patroni/api.py
  patroni/dcs/__init__.py
  patroni/dcs/zookeeper.py
  tests/test_zookeeper.py
Labels: bug, refactoring

#2907 Allow to specify psycopg* in extras and switch to `build`
  .github/workflows/release.yaml
  README.rst
  docs/installation.rst
  patroni/__init__.py
  patroni/__main__.py
  setup.py
  tests/test_patroni.py
Labels: bug, enhancement, ci, refactoring, codestyle

#2891 Further work on permanent physical slots
  docs/dynamic_configuration.rst
  features/dcs_failsafe_mode.feature
  features/environment.py
  features/ignored_slots.feature
  features/permanent_slots.feature
  features/standby_cluster.feature
  features/steps/basic_replication.py
  features/steps/slots.py
  patroni/dcs/__init__.py
  patroni/ha.py
  patroni/postgresql/__init__.py
  patroni/postgresql/slots.py
  patroni/utils.py
  tests/test_ha.py
  tests/test_slots.py
Labels: enhancement

#2920 Remove user creation related docs
  docs/ENVIRONMENT.rst
  docs/yaml_configuration.rst
  postgres0.yml
  postgres1.yml
  postgres2.yml
Labels: documentation

#2922 get rid of stale comment of get_cluster
  patroni/dcs/__init__.py
Labels: codestyle

#2926 Add capability of specifying namespace through `--dcs` argument
  docs/patronictl.rst
  patroni/ctl.py
Labels: enhancement

#2780 Feature: failover priority
  docs/yaml_configuration.rst
  features/basic_replication.feature
  features/priority_failover.feature
  features/steps/basic_replication.py
  patroni/config.py
  patroni/ha.py
  patroni/tags.py
  patroni/validator.py
  tests/test_config.py
  tests/test_ha.py
  tests/test_patroni.py
  tests/test_validator.py
Labels: needs review, new feature

#2928 Improve formatting of generated config
  patroni/config_generator.py
  patroni/validator.py
  tests/test_config_generator.py
Labels: enhancement

#2927 Add support for additional parameters on custom bootstrap
  docs/replica_bootstrap.rst
  features/backup_restore.py
  features/environment.py
  features/steps/standby_cluster.py
  patroni/postgresql/bootstrap.py
Labels: enhancement

#2932 Add ability to pass auth_data to zk client
  docs/ENVIRONMENT.rst
  docs/yaml_configuration.rst
  patroni/config.py
  patroni/dcs/zookeeper.py
  patroni/validator.py
Labels: enhancement
