Repository patroni/patroni, pull requests merged in 2023-04, with the labels that each got.

#2628 Factor out global configuration into a dedicated class
  patroni/api.py
  patroni/config.py
  patroni/ctl.py
  patroni/dcs/__init__.py
  patroni/ha.py
  patroni/postgresql/__init__.py
  patroni/postgresql/config.py
  patroni/utils.py
  tests/test_api.py
  tests/test_config.py
  tests/test_ctl.py
  tests/test_etcd.py
  tests/test_ha.py
  tests/test_postgresql.py
Labels: refactoring, codestyle

#2627 Ignore D401 in flake8-docstrings
  features/environment.py
  features/steps/basic_replication.py
  features/steps/citus.py
  features/steps/standby_cluster.py
  patroni/api.py
  patroni/config.py
  patroni/ctl.py
  patroni/dcs/__init__.py
  patroni/dcs/consul.py
  patroni/dcs/etcd.py
  patroni/dcs/etcd3.py
  patroni/dcs/kubernetes.py
  patroni/dcs/raft.py
  patroni/dcs/zookeeper.py
  patroni/ha.py
  patroni/postgresql/__init__.py
  patroni/postgresql/cancellable.py
  patroni/postgresql/citus.py
  patroni/postgresql/config.py
  patroni/postgresql/rewind.py
  patroni/postgresql/slots.py
  patroni/postgresql/sync.py
  patroni/validator.py
  tests/test_api.py
  tests/test_bootstrap.py
  tests/test_consul.py
  tests/test_ctl.py
  tests/test_etcd.py
  tests/test_etcd3.py
  tests/test_kubernetes.py
  tests/test_postgresql.py
  tests/test_raft.py
  tests/test_rewind.py
  tests/test_validator.py
  tests/test_watchdog.py
  tests/test_zookeeper.py
  tox.ini
Labels: codestyle

#2629 Introduce patroni.collections
  patroni/collections.py
  patroni/config.py
  patroni/postgresql/config.py
  patroni/postgresql/sync.py
  patroni/postgresql/validator.py
  tests/test_postgresql.py
Labels: refactoring

#2631 More use of CaseInsensitiveSet
  patroni/collections.py
  patroni/config.py
  patroni/dcs/__init__.py
  patroni/dcs/kubernetes.py
  patroni/ha.py
  patroni/postgresql/__init__.py
  patroni/postgresql/sync.py
  tests/test_ha.py
  tests/test_sync.py
Labels: refactoring, codestyle

#2639 Cover `etcd3` in `parse_dcs` function
  patroni/ctl.py
  tests/test_ctl.py
Labels: bug

#2645 Attempt to reduce behave flakiness on MacOS
  features/ignored_slots.feature
  features/patroni_api.feature
Labels: ci

#2634 Add docstrings and type annotations to `patroni/psycopg.py`
  patroni/psycopg.py
Labels: codestyle

#2649 Render nested lists correctly in settings docs
  docs/SETTINGS.rst
Labels: documentation

#2642 Add before stop hook
  docs/SETTINGS.rst
  patroni/postgresql/__init__.py
  tests/test_postgresql.py
Labels: new feature
