Repository patroni/patroni, pull requests merged in 2023-07, with the labels that each got.

#2722 REST API would not reload SSL certificate upon receiving an SIGHUP
  patroni/api.py
  tests/test_api.py
Labels: bug

#2725 Use full names for contributors in the release notes
  docs/releases.rst
Labels: documentation

#2736 Compatibility with click==8.1.4
  .github/workflows/tests.yaml
  patroni/ctl.py
Labels: codestyle

#2732 Update .gitignore to include common venv/data patterns
  .gitignore
Labels: enhancement

#2727 Set encoding on open call in setup.py
  README.rst
  setup.py
Labels: documentation, refactoring

#2737 Check py files in features with flake8
  setup.py
Labels: codestyle

#2728 Reduce flakiness of citus behave tests
  features/citus.feature
  features/steps/citus.py
Labels: refactoring

#2729 Make sure the version_prefix for etcd3 is set to /v3beta
  patroni/dcs/etcd.py
  patroni/dcs/etcd3.py
Labels: bug

#2730 Use quorum read in patronictl if it is possible
  patroni/dcs/consul.py
  patroni/dcs/etcd.py
  patroni/dcs/etcd3.py
  patroni/dcs/kubernetes.py
Labels: enhancement

#2734 Allow integer gucs without units in validation
  features/patroni_api.feature
  patroni/utils.py
  patroni/validator.py
Labels: bug

#2724 Prevent splitbrain from duplicate names in configuration
  features/basic_replication.feature
  features/environment.py
  features/steps/basic_replication.py
  patroni/__main__.py
  tests/test_patroni.py
Labels: enhancement

#2726 Start postgres not in recovery in some cases
  features/basic_replication.feature
  features/recovery.feature
  patroni/ha.py
  tests/test_ha.py
Labels: enhancement

#2741 A few fixes in synchronous_mode
  patroni/ha.py
  patroni/postgresql/bootstrap.py
  patroni/postgresql/sync.py
  tests/test_ha.py
Labels: bug, enhancement

#2733 Make it visible replication state on standbys
  docs/rest_api.rst
  features/standby_cluster.feature
  patroni/api.py
  patroni/ctl.py
  patroni/ha.py
  patroni/postgresql/__init__.py
  patroni/postgresql/config.py
  patroni/utils.py
  tests/__init__.py
  tests/test_api.py
  tests/test_ha.py
  tests/test_rewind.py
  tests/test_slots.py
Labels: enhancement

#2760 Fix typo in yml files
  postgres0.yml
  postgres1.yml
  postgres2.yml
Labels: typo

#2761 Validate more parameters in the config file
  patroni/validator.py
  tests/test_validator.py
Labels: enhancement

#2763 Start primary back when it crashed with "in crash recovery" state
  patroni/ha.py
Labels: bug

#2766 Run archive_command through shell
  patroni/postgresql/rewind.py
  tests/test_rewind.py
Labels: bug

#2770 Fix Dockerfile_s
  Dockerfile
  Dockerfile.citus
Labels: bug

#2771 Skip flaky scenario when running with Raft
  features/basic_replication.feature
  features/environment.py
Labels: ci

#2746 Refactor get replication slots
  patroni/dcs/__init__.py
Labels: refactoring, codestyle

#2769 Fix manual failover/switchover checks
  patroni/ha.py
Labels: bug

#2749 Refactor `check_logical_slots_readiness` split to reduce complexity
  patroni/postgresql/slots.py
  tests/test_slots.py
Labels: refactoring, codestyle

#2747 Refactor get_dcs
  patroni/dcs/__init__.py
  tests/test_ha.py
Labels: refactoring, codestyle

#2768 Fixes in `patroni.request`
  docs/ENVIRONMENT.rst
  docs/yaml_configuration.rst
  features/environment.py
  patroni/config.py
  patroni/ctl.py
  patroni/request.py
  tests/test_ctl.py
  typings/urllib3/__init__.pyi
  typings/urllib3/connectionpool.pyi
Labels: bug, enhancement, documentation

#2659 Make pod role label configurable
  docs/ENVIRONMENT.rst
  docs/kubernetes.rst
  docs/yaml_configuration.rst
  patroni/config.py
  patroni/dcs/kubernetes.py
  patroni/validator.py
  tests/test_kubernetes.py
Labels: new feature

#2773 Fix `in_recovery` check
  patroni/ha.py
  tests/test_ha.py
Labels: bug

#2775 Fix patronictl list
  patroni/ctl.py
  tests/test_ctl.py
Labels: bug

#2782 Avoid unnecessary updates of /status key
  patroni/dcs/__init__.py
Labels: bug

#2776 Fix pg_rewind behaviour after pause
  patroni/ha.py
  patroni/postgresql/__init__.py
  patroni/postgresql/rewind.py
Labels: bug

#2787 Don't allow stale primary to win the leader race
  patroni/ha.py
  tests/test_ha.py
Labels: enhancement

#2791 Warn about failed validation configuration parameters
  patroni/config.py
  patroni/postgresql/config.py
  patroni/validator.py
  tests/test_config.py
Labels: enhancement

#2788 Fix `replicatefrom` tag in `postgres2.yml`
  postgres2.yml
Labels: typo

#2790 Refactor replica_list
  patroni/postgresql/sync.py
Labels: refactoring
