Repository patroni/patroni, pull requests merged in 2023-01, with the labels that each got.

#2515 Fix behave tests on GH actions MacOS
  .github/workflows/install_deps.py
  .github/workflows/run_tests.py
  .github/workflows/tests.yaml
Labels: ci

#2379 DCS failsafe mode
  docs/SETTINGS.rst
  docs/dcs_failsafe_mode.rst
  docs/index.rst
  features/dcs_failsafe_mode.feature
  features/environment.py
  features/steps/dcs_failsafe_mode.py
  features/steps/patroni_api.py
  patroni/api.py
  patroni/config.py
  patroni/dcs/__init__.py
  patroni/dcs/kubernetes.py
  patroni/ha.py
  tests/__init__.py
  tests/test_api.py
  tests/test_etcd.py
  tests/test_ha.py
  tests/test_patroni.py
Labels: needs review, new feature

#2528 Submit coverage to codacy only if secret is available
  .github/workflows/tests.yaml
Labels: bug, ci

#2502 Suppress recurring errors when dropping unknown but active replication slots
  patroni/postgresql/slots.py
Labels: enhancement

#2531 Clean pg_replslot/ after pg_rewind
  patroni/postgresql/misc.py
  patroni/postgresql/rewind.py
  patroni/postgresql/slots.py
  tests/test_ha.py
  tests/test_rewind.py
  tests/test_slots.py
Labels: enhancement

#2471 fix: only keep latest failed data directory
  patroni/postgresql/__init__.py
  tests/test_postgresql.py
Labels: enhancement

#2534 Refactor drop_replication_slot() and _drop_incorrect_slots()
  patroni/postgresql/slots.py
  tests/__init__.py
  tests/test_slots.py
Labels: enhancement

#2532 Fixes and improvements in failsafe
  features/dcs_failsafe_mode.feature
  features/environment.py
  patroni/ha.py
  tests/test_ha.py
Labels: bug

#2524 Enhanced sync connections check
  patroni/ha.py
  patroni/postgresql/__init__.py
  patroni/postgresql/config.py
  patroni/postgresql/sync.py
  tests/__init__.py
  tests/test_ha.py
  tests/test_postgresql.py
  tests/test_sync.py
Labels: enhancement

#2538 Check unexpected exceptions in Patroni logs after behave
  .github/workflows/tests.yaml
  features/environment.py
Labels: ci

#2541 Change master->primary/leader/member
  docs/ENVIRONMENT.rst
  docs/SETTINGS.rst
  docs/citus.rst
  docs/kubernetes.rst
  docs/replica_bootstrap.rst
  docs/rest_api.rst
  extras/confd/templates/haproxy.tmpl
  features/basic_replication.feature
  features/dcs_failsafe_mode.feature
  features/environment.py
  features/ignored_slots.feature
  features/patroni_api.feature
  features/standby_cluster.feature
  features/steps/basic_replication.py
  features/steps/dcs_failsafe_mode.py
  patroni/api.py
  patroni/config.py
  patroni/ctl.py
  patroni/dcs/__init__.py
  patroni/dcs/consul.py
  patroni/dcs/etcd3.py
  patroni/dcs/exhibitor.py
  patroni/dcs/kubernetes.py
  patroni/ha.py
  patroni/postgresql/__init__.py
  patroni/postgresql/bootstrap.py
  patroni/postgresql/citus.py
  patroni/postgresql/config.py
  patroni/postgresql/rewind.py
  patroni/postgresql/sync.py
  patroni/scripts/wale_restore.py
  postgres0.yml
  tests/__init__.py
  tests/test_api.py
  tests/test_aws.py
  tests/test_config.py
  tests/test_consul.py
  tests/test_ctl.py
  tests/test_ha.py
  tests/test_kubernetes.py
  tests/test_postgresql.py
  tests/test_rewind.py
  tests/test_slots.py
  tests/test_wale_restore.py
Labels: help wanted, needs review
