Repository patroni/patroni, pull requests merged in 2023-05, with the labels that each got.

#2650 Update REWIND_USERNAME,PASSWORD optional tag in ENVIRONMENT.rst file
  docs/ENVIRONMENT.rst
  docs/SETTINGS.rst
Labels: documentation

#2661 Documentation improvements
  README.rst
  docs/ENVIRONMENT.rst
  docs/README.rst
  docs/SETTINGS.rst
  docs/conf.py
  docs/dcs_failsafe_mode.rst
  docs/dynamic_configuration.rst
  docs/ha_multi_dc.rst
  docs/index.rst
  docs/patroni_configuration.rst
  docs/releases.rst
  docs/replication_modes.rst
  docs/rest_api.rst
  docs/security.rst
  docs/yaml_configuration.rst
Labels: documentation

#2669 Refactor write_sync_state()
  patroni/dcs/__init__.py
  patroni/dcs/consul.py
  patroni/dcs/etcd.py
  patroni/dcs/etcd3.py
  patroni/dcs/kubernetes.py
  patroni/dcs/raft.py
  patroni/dcs/zookeeper.py
  patroni/ha.py
  tests/test_consul.py
  tests/test_etcd.py
  tests/test_etcd3.py
  tests/test_ha.py
  tests/test_kubernetes.py
  tests/test_raft.py
Labels: refactoring

#2648 Add docstrings and type hints to `patroni/api.py`
  patroni/api.py
  tests/test_api.py
Labels: codestyle

#2675 Enable pyright job for every commit
  .github/workflows/tests.yaml
  patroni/api.py
  patroni/config.py
  patroni/ctl.py
  patroni/dcs/__init__.py
  patroni/dcs/consul.py
  patroni/dcs/etcd.py
  patroni/dcs/etcd3.py
  patroni/dcs/kubernetes.py
  patroni/dcs/raft.py
  patroni/dcs/zookeeper.py
  patroni/ha.py
  patroni/log.py
  patroni/postgresql/__init__.py
  patroni/postgresql/config.py
  patroni/postgresql/sync.py
  patroni/scripts/wale_restore.py
  patroni/validator.py
  patroni/watchdog/base.py
  patroni/watchdog/linux.py
  pyrightconfig.json
  tests/test_ha.py
  tests/test_postgresql.py
Labels: ci, codestyle

#2678 Validate-config fixes
  docs/yaml_configuration.rst
  patroni/validator.py
  tests/test_validator.py
Labels: bug, documentation

#2682 Fix pyright complaints about partner_addrs
  .github/workflows/tests.yaml
  patroni/dcs/raft.py
Labels: ci, codestyle

#2683 Fix dev Dockerfile.citus for arm
  Dockerfile.citus
  kubernetes/Dockerfile.citus
Labels: bug

#2680 Change PostgreSQL Slack invite link
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  README.rst
  docs/CONTRIBUTING.rst
Labels: documentation

#2684 Remove bootstrap.pg_hba
  Dockerfile
  Dockerfile.citus
  docs/dynamic_configuration.rst
  docs/yaml_configuration.rst
  kubernetes/Dockerfile.citus
  kubernetes/entrypoint.sh
  patroni/validator.py
  postgres0.yml
  postgres1.yml
  postgres2.yml
  tests/test_validator.py
Labels: documentation, deprecation

#2685 Make bootstrap.initdb optional
  docs/yaml_configuration.rst
  patroni/validator.py
Labels: bug, documentation

#2689 Little fixes in etcd3 and kubernetes
  patroni/dcs/etcd3.py
  patroni/dcs/kubernetes.py
  tests/test_etcd3.py
  tests/test_kubernetes.py
Labels: bug, codestyle

#2691 Subtle README fix
  docs/README.rst
Labels: documentation

#2690 Refactor update_leader interface
  patroni/dcs/__init__.py
  patroni/dcs/consul.py
  patroni/dcs/etcd.py
  patroni/dcs/etcd3.py
  patroni/dcs/kubernetes.py
  patroni/dcs/raft.py
  patroni/dcs/zookeeper.py
  patroni/ha.py
  tests/test_consul.py
  tests/test_etcd.py
  tests/test_etcd3.py
  tests/test_kubernetes.py
  tests/test_raft.py
  tests/test_zookeeper.py
Labels: refactoring

#2694 Introduce Retry.ensure_deadline() method
  patroni/dcs/consul.py
  patroni/dcs/etcd3.py
  patroni/dcs/kubernetes.py
  patroni/utils.py
Labels: refactoring

#2697 Refactor daemon entrypoints
  patroni/__main__.py
  patroni/daemon.py
  patroni/raft_controller.py
  tests/test_patroni.py
Labels: refactoring

#2692 Add support for custom Postgres binary names
  docs/ENVIRONMENT.rst
  docs/yaml_configuration.rst
  patroni/postgresql/__init__.py
  patroni/validator.py
  tests/test_validator.py
Labels: new feature

#2671 Extend Postgres GUCs validator
  patroni.spec
  patroni/postgresql/__init__.py
  patroni/postgresql/available_parameters/0_postgres.yml
  patroni/postgresql/config.py
  patroni/postgresql/validator.py
  setup.py
  tests/__init__.py
  tests/test_bootstrap.py
  tests/test_patroni.py
  tests/test_postgresql.py
  tests/test_sync.py
Labels: enhancement, new feature, refactoring
