Repository patroni/patroni, pull requests merged in 2023-09, with the labels that each got.

#2845 `patronictl --help` was showing `ctl` function's docstring
  patroni/ctl.py
Labels: bug

#2832 Fix bug with kubernetes.standby_leader_label_value
  docs/ENVIRONMENT.rst
  docs/yaml_configuration.rst
  patroni/dcs/kubernetes.py
  tests/test_kubernetes.py
Labels: bug

#2849 Debian docker image pip error
  .gitignore
  features/Dockerfile
Labels: ci

#2846 Enreach some endpoints with the scope and name
  docs/rest_api.rst
  patroni/api.py
Labels: enhancement

#2833 Introduce a dedicated postgres connection for REST API
  patroni/api.py
  tests/test_api.py
Labels: enhancement

#2840 Return system id to the ctl list title
  patroni/ctl.py
  tests/test_ctl.py
Labels: bug

#2850 Override write_leader_optime method in K8s implementation
  patroni/dcs/kubernetes.py
  tests/test_kubernetes.py
Labels: bug

#2848 Don't start stopped postgres in pause
  patroni/postgresql/config.py
  tests/test_postgresql.py
Labels: bug

#2851 Refactor replication slots handling
  patroni/dcs/__init__.py
  patroni/postgresql/slots.py
  tests/__init__.py
  tests/test_slots.py
Labels: bug, refactoring

#2854 Extend documentation with package installation and upgrade process
  docs/README.rst
  docs/index.rst
  docs/installation.rst
Labels: documentation

#2843 Document how to change Postgres settings that touch shared memory
  docs/patroni_configuration.rst
Labels: documentation

#2784 Ensure strict failover/switchover definition difference
  docs/pause.rst
  docs/rest_api.rst
  patroni/api.py
  patroni/ctl.py
  patroni/ha.py
  tests/test_api.py
  tests/test_ctl.py
  tests/test_ha.py
Labels: enhancement, documentation, refactoring

#2853 Introduce Status class
  patroni/dcs/__init__.py
  patroni/dcs/consul.py
  patroni/dcs/etcd.py
  patroni/dcs/etcd3.py
  patroni/dcs/kubernetes.py
  patroni/dcs/raft.py
  patroni/dcs/zookeeper.py
  patroni/ha.py
  tests/test_ha.py
  tests/test_slots.py
Labels: refactoring

#2859 Fix bug in `patronictl query` command
  patroni/ctl.py
  tests/test_ctl.py
Labels: bug

#2861 Always store integer CMDLINE_OPTIONS config values as int
  patroni/config.py
  patroni/postgresql/citus.py
  tests/test_bootstrap.py
  tests/test_config.py
  tests/test_postgresql.py
Labels: bug

#2857 Update supported Postgres versions
  .github/workflows/install_deps.py
  .github/workflows/mapping.py
  README.rst
  docs/index.rst
Labels: documentation

#2871 Bump pyright version
  .github/workflows/tests.yaml
  patroni/dcs/etcd3.py
  patroni/dcs/kubernetes.py
  patroni/dcs/zookeeper.py
  patroni/ha.py
  patroni/postgresql/__init__.py
  patroni/postgresql/config.py
  patroni/postgresql/slots.py
Labels: ci, codestyle

#2873 Stick with sphinx_rtd_theme
  docs/conf.py
Labels: documentation

#2852 Permanent physical slots on standby nodes
  docs/dynamic_configuration.rst
  features/ignored_slots.feature
  features/permanent_slots.feature
  features/standby_cluster.feature
  features/steps/slots.py
  patroni/dcs/__init__.py
  patroni/dcs/zookeeper.py
  patroni/postgresql/__init__.py
  patroni/postgresql/slots.py
  tests/__init__.py
  tests/test_slots.py
Labels: enhancement, new feature

#2878 Silence annoying warnings when checking for node uniqueness
  patroni/__main__.py
  tests/test_patroni.py
Labels: bug

#2883 Bugfix for GUC's values with units
  patroni/config.py
  tests/test_config.py
Labels: bug

#2884 Take into account current role when deciding on removal of member ZNode
  features/patroni_api.feature
  patroni/dcs/zookeeper.py
  tests/test_zookeeper.py
Labels: bug, ci

#2876 Read GUC's values when joining running Postgres
  patroni/config_generator.py
  patroni/postgresql/__init__.py
  patroni/postgresql/config.py
  tests/__init__.py
  tests/test_postgresql.py
Labels: bug

#2877 Detect and solve inconsistency between /sync and actual sync nodes
  patroni/ha.py
  tests/test_ha.py
Labels: bug

#2887 Contributing docs improvements
  docs/contributing_guidelines.rst
Labels: documentation

#2888 Don't fail if pg_hba/pg_ident contain comment lines
  patroni/postgresql/config.py
Labels: enhancement
