Repository patroni/patroni, pull requests merged in 2023-11, with the labels that each got.

#2933 Add a FAQ page to the docs
  docs/contributing_guidelines.rst
  docs/faq.rst
  docs/index.rst
  docs/patroni_configuration.rst
  docs/rest_api.rst
Labels: documentation

#2938 Limit accepted values for --format argument
  patroni/ctl.py
Labels: bug

#2939 Verify that replica nodes received checkpoint LSN on shutdown
  patroni/ha.py
  patroni/postgresql/__init__.py
  tests/test_ha.py
  tests/test_postgresql.py
Labels: bug

#2943 Fix Etcd v2 with Citus
  patroni/dcs/__init__.py
  patroni/dcs/consul.py
  patroni/dcs/etcd.py
  tests/test_etcd.py
Labels: bug

#2944 Fix pg_rewind behavior with Postgres v16+
  patroni/postgresql/rewind.py
  tests/test_rewind.py
Labels: bug

#2948 Fix bug with custom bootstrap
  patroni/postgresql/bootstrap.py
  tests/test_bootstrap.py
Labels: bug

#2945 Get rid of pass_obj() in most of patronictl commands
  patroni/ctl.py
  tests/test_ctl.py
Labels: refactoring

#2951 Compatibility with antient mock
  tests/test_barman_recover.py
Labels: ci

#2952 Bump pyright to 1.1.336
  .github/workflows/tests.yaml
  patroni/validator.py
  typings/urllib3/_collections.pyi
Labels: ci, codestyle

#2954 Factor out dynamic class finder/loader to a dedicated file
  patroni/dcs/__init__.py
  patroni/dynamic_loader.py
  tests/test_ctl.py
Labels: refactoring

#2935 Make GlobalConfig really global
  patroni/api.py
  patroni/config.py
  patroni/ctl.py
  patroni/dcs/__init__.py
  patroni/global_config.py
  patroni/ha.py
  patroni/postgresql/__init__.py
  patroni/postgresql/config.py
  patroni/postgresql/slots.py
  patroni/postgresql/sync.py
  patroni/utils.py
  tests/test_api.py
  tests/test_config.py
  tests/test_ctl.py
  tests/test_ha.py
  tests/test_patroni.py
  tests/test_postgresql.py
  tests/test_slots.py
  tests/test_sync.py
Labels: refactoring

#2961 [doc]: fix typos
  patroni/ctl.py
Labels: codestyle

#2965 [doc]Update README.rst
  README.rst
Labels: documentation

#2964 Fix Citus transaction rollback condition check
  features/steps/citus.py
Labels: ci
