Repository patroni/patroni, pull requests merged in 2023-06, with the labels that each got.

#2707 Fix kubernetes behave tests
  features/environment.py
Labels: ci

#2687 Add docstrings to `patroni.ctl`
  patroni/ctl.py
Labels: codestyle

#2698 Add docstrings to `patroni.__init__`
  patroni/__init__.py
Labels: codestyle

#2702 Add docstrings to `patroni.collections`
  patroni/collections.py
Labels: codestyle

#2704 Add docstrings to `patroni.async_executor`
  patroni/async_executor.py
Labels: codestyle

#2710 Fix a few concurrency bugs in Citus support
  patroni/postgresql/citus.py
  tests/test_citus.py
Labels: bug, citus

#2718 Compatibility with python 3.11
  patroni/postgresql/config.py
Labels: bug

#2716 Update GUC's validator for PG16 beta1
  patroni/postgresql/available_parameters/0_postgres.yml
Labels: enhancement

#2723 Update request_queue_size feature authors
  docs/releases.rst
Labels: documentation
