Repository patroni/patroni, pull requests merged in 2023-08, with the labels that each got.

#2794 Fix bug in the Cluster class
  patroni/dcs/__init__.py
Labels: bug

#2795 Fix behaviour of replicas in standby cluster in pause
  patroni/ha.py
Labels: bug

#2797 Enhance docs of `slots` dynamic configuration
  docs/dynamic_configuration.rst
Labels: documentation

#2781 Set permissions for files and directories created in PGDATA
  patroni/config.py
  patroni/file_perm.py
  patroni/postgresql/config.py
  patroni/postgresql/slots.py
  tests/test_config.py
  tests/test_file_perm.py
  tests/test_ha.py
  tests/test_postgresql.py
Labels: bug, enhancement

#2796 Refactor docs about migration to Patroni
  docs/existing_data.rst
Labels: documentation

#2802 Mock request() method when running tests
  patroni/__main__.py
  tests/test_patroni.py
Labels: enhancement

#2803 reset failsafe state when promote
  patroni/ha.py
Labels: bug

#2777 Add docs to `patroni.dcs.__init__.py`
  patroni/dcs/__init__.py
Labels: refactoring, codestyle

#2778 Add docstrings to `patroni.postgresql.slots.py`
  patroni/postgresql/slots.py
  tests/test_slots.py
Labels: refactoring, codestyle

#2804 Refactor is_failover_possible()
  patroni/ha.py
  tests/test_ha.py
Labels: refactoring

#2809 Rename Postgresql.is_leader() to is_primary()
  patroni/ha.py
  patroni/postgresql/__init__.py
  patroni/postgresql/citus.py
  patroni/postgresql/rewind.py
  patroni/postgresql/slots.py
  patroni/postgresql/sync.py
  tests/test_ha.py
  tests/test_postgresql.py
  tests/test_slots.py
Labels: refactoring, codestyle

#2808 Silence useless warnings in patronictl
  patroni/config.py
Labels: bug, enhancement

#2810 Refactor delete_leader interface
  patroni/dcs/__init__.py
  patroni/dcs/consul.py
  patroni/dcs/etcd.py
  patroni/dcs/etcd3.py
  patroni/dcs/kubernetes.py
  patroni/dcs/raft.py
  patroni/dcs/zookeeper.py
  patroni/ha.py
  tests/test_consul.py
  tests/test_etcd.py
  tests/test_etcd3.py
  tests/test_kubernetes.py
  tests/test_raft.py
  tests/test_zookeeper.py
Labels: refactoring

#2807 [Refactor] Rename _is_leader to _leader_expiry
  patroni/ha.py
Labels: refactoring, codestyle

#2811 Make docs more clear on changes to the `bootstrap.dcs` section
  docs/yaml_configuration.rst
Labels: documentation

#2813 Use pg_current_wal_flush_lsn() starting from 9.6
  patroni/api.py
  patroni/postgresql/__init__.py
  patroni/postgresql/sync.py
  tests/test_api.py
  tests/test_postgresql.py
Labels: enhancement

#2701 Add docstrings to `patroni.__main__`
  patroni/__main__.py
Labels: codestyle

#2699 Generate API docs from code with sphinx autodoc
  .github/workflows/tests.yaml
  .gitignore
  .readthedocs.yaml
  docs/CONTRIBUTING.rst
  docs/conf.py
  docs/contributing_guidelines.rst
  docs/ha_multi_dc.rst
  docs/index.rst
  docs/yaml_configuration.rst
  patroni/api.py
  patroni/ha.py
  patroni/log.py
  patroni/postgresql/__init__.py
  patroni/postgresql/citus.py
  patroni/postgresql/slots.py
  patroni/postgresql/sync.py
  patroni/postgresql/validator.py
  patroni/psycopg.py
  patroni/request.py
  patroni/utils.py
  patroni/validator.py
  requirements.docs.txt
  tox.ini
Labels: documentation

#2708 Add docstrings to `patroni.config`
  docs/patroni_configuration.rst
  docs/rest_api.rst
  patroni/config.py
Labels: refactoring, codestyle

#2820 Explicitly enable synchronous mode
  patroni/ha.py
  tests/test_ha.py
Labels: bug

#2818 Fix `IntValidator` regarding validation of value `0`
  patroni/validator.py
Labels: bug

#2821 Remove Python 2 install instructions from README
  README.rst
Labels: documentation

#2822 Remove Python 2 install instructions from docs/README
  README.rst
  docs/README.rst
Labels: documentation

#2816 Don't return logical slots for standby cluster
  patroni/dcs/__init__.py
  patroni/postgresql/__init__.py
  patroni/postgresql/slots.py
  tests/test_slots.py
Labels: bug

#2824 Update api docs examples
  docs/rest_api.rst
Labels: documentation

#2826 Remove accidentally added .DS_Store
  .gitignore
  docs/.DS_Store
Labels: documentation

#2825 Pin sphinx_rtd_theme to >1
  requirements.docs.txt
Labels: bug, documentation

#2823 Factor out tags handling into a dedicated class
  patroni/__main__.py
  patroni/dcs/__init__.py
  patroni/ha.py
  patroni/postgresql/sync.py
  patroni/tags.py
  tests/test_api.py
  tests/test_ha.py
  tests/test_patroni.py
Labels: refactoring
