Repository patroni/patroni, pull requests merged in 2024-06, with the labels that each got.

#3073 Doc improvement: mention use of gRPC gateway with EtcdV3
  docs/ENVIRONMENT.rst
  docs/yaml_configuration.rst
Labels: documentation

#3069 Refactor format_dsn() method
  patroni/postgresql/bootstrap.py
  patroni/postgresql/config.py
  patroni/postgresql/rewind.py
  tests/test_rewind.py
Labels: refactoring

#3072 Fix infinite recursion in in replicatefrom tags
  docs/yaml_configuration.rst
  patroni/dcs/__init__.py
  tests/test_slots.py
Labels: bug

#3076 Compatibility with 17-beta1
  patroni/postgresql/available_parameters/0_postgres.yml
  patroni/postgresql/config.py
  patroni/postgresql/postmaster.py
  tests/test_postgresql.py
  tests/test_postmaster.py
Labels: compatibility

#3074 drop dependency on ancient mock
  .github/workflows/install_deps.py
  requirements.dev.txt
  tests/__init__.py
  tests/test_api.py
  tests/test_async_executor.py
  tests/test_aws.py
  tests/test_barman.py
  tests/test_bootstrap.py
  tests/test_callback_executor.py
  tests/test_cancellable.py
  tests/test_citus.py
  tests/test_config.py
  tests/test_config_generator.py
  tests/test_consul.py
  tests/test_ctl.py
  tests/test_etcd.py
  tests/test_etcd3.py
  tests/test_exhibitor.py
  tests/test_file_perm.py
  tests/test_ha.py
  tests/test_kubernetes.py
  tests/test_log.py
  tests/test_patroni.py
  tests/test_postgresql.py
  tests/test_postmaster.py
  tests/test_raft.py
  tests/test_raft_controller.py
  tests/test_rewind.py
  tests/test_slots.py
  tests/test_sync.py
  tests/test_utils.py
  tests/test_validator.py
  tests/test_wale_restore.py
  tests/test_watchdog.py
  tests/test_zookeeper.py
  tox.ini
Labels: refactoring

#3005 Re-enable SSL for MacOS GH action runners
  features/environment.py
Labels: ci

#3079 Standby cluster can't have synchronous nodes
  patroni/utils.py
  tests/test_ctl.py
Labels: bug

#3081 Adjust allow_in_place_tablespaces availability
  patroni/postgresql/available_parameters/0_postgres.yml
Labels: bug

#3082 Don't socket.getaddrinfo() from config_generator.py
  patroni/config_generator.py
  tests/test_config_generator.py
Labels: enhancement, ci

#3086 Change all links and org references
  README.rst
  docker-compose-citus.yml
  docker-compose.yml
  docs/README.rst
  docs/citus.rst
  docs/conf.py
  docs/contributing_guidelines.rst
  docs/kubernetes.rst
  docs/releases.rst
  kubernetes/Dockerfile
  kubernetes/Dockerfile.citus
  kubernetes/openshift-example/README.md
  setup.py
Labels: ci, documentation
