Repository patroni/patroni, pull requests merged in 2024-09, with the labels that each got.

#3152 Handle exception from iterdir while discovering static files
  patroni/postgresql/available_parameters/__init__.py
  tests/test_postgresql.py
Labels: bug

#3149 Fix unhandled DCSError cause patroni exit during startup phase
  patroni/__main__.py
  tests/test_patroni.py
Labels: bug

#3160 Use None instead of empty string in socket.getaddrinfo() port
  patroni/validator.py
Labels: bug, compatibility

#3157 Explicitly include CMDLINE_OPTIONS GUCs when querying pg_settings
  patroni/postgresql/config.py
Labels: bug

#3156 Make sure sphinx doc attributes are available before trying to access them
  docs/conf.py
Labels: documentation, compatibility

#3161 Fix bug in quote_standby_name() function
  patroni/postgresql/sync.py
  tests/test_sync.py
Labels: bug

#3162 Use names with "unusual" symbols in behave tests
  features/basic_replication.feature
  features/cascading_replication.feature
  features/citus.feature
  features/custom_bootstrap.feature
  features/dcs_failsafe_mode.feature
  features/ignored_slots.feature
  features/nostream_node.feature
  features/patroni_api.feature
  features/permanent_slots.feature
  features/priority_failover.feature
  features/quorum_commit.feature
  features/recovery.feature
  features/standby_cluster.feature
  features/steps/basic_replication.py
  features/steps/cascading_replication.py
  features/steps/citus.py
  features/steps/custom_bootstrap.py
  features/steps/dcs_failsafe_mode.py
  features/steps/patroni_api.py
  features/steps/quorum_commit.py
  features/steps/slots.py
  features/steps/standby_cluster.py
  features/steps/watchdog.py
  features/watchdog.feature
Labels: ci

#3168 Fix flake8 for tests directory
  setup.py
  tests/test_ha.py
  tests/test_patroni.py
  tests/test_postgresql.py
  tests/test_slots.py
Labels: ci, codestyle

#3169 Don't retains member slots on nodes with nofailover tag
  features/permanent_slots.feature
  patroni/dcs/__init__.py
  tests/test_slots.py
Labels: bug

#3167 Follow up on #3148
  patroni/dcs/__init__.py
  tests/test_slots.py
Labels: bug

#3173 Add support of sslnegotiation client-side connection option
  .github/workflows/install_deps.py
  .github/workflows/mapping.py
  README.rst
  docs/index.rst
  patroni/config.py
  patroni/config_generator.py
  patroni/postgresql/config.py
  tests/test_config_generator.py
  tests/test_postgresql.py
Labels: enhancement, documentation
