Repository patroni/patroni, pull requests merged in 2024-01, with the labels that each got.

#2992 Not filter out contradictory nofailover tag
  features/priority_failover.feature
  features/steps/basic_replication.py
  features/steps/patroni_api.py
  patroni/config.py
  patroni/tags.py
  postgres0.yml
  postgres1.yml
  postgres2.yml
  tests/test_config.py
  tests/test_patroni.py
Labels: bug

#2996 call freeze_support in main module to solve pyinstaller frozen issue
  patroni/__main__.py
Labels: bug

#3000 Close the doors for a possible future bug in the config generator
  patroni/config_generator.py
Labels: bug

#2998 Restore recovery GUCs when joining running standby
  patroni/postgresql/config.py
  tests/test_postgresql.py
Labels: bug

#3004 Optimize priority failover behave tests
  features/priority_failover.feature
  features/steps/basic_replication.py
Labels: ci

#3003 Fixes around pending_restart flag
  patroni/postgresql/config.py
  tests/__init__.py
  tests/test_postgresql.py
Labels: enhancement

#2982 Add JSON log format to logging configuration
  docs/ENVIRONMENT.rst
  docs/installation.rst
  docs/yaml_configuration.rst
  patroni/config.py
  patroni/config_generator.py
  patroni/log.py
  patroni/validator.py
  requirements.txt
  setup.py
  tests/test_config.py
  tests/test_config_generator.py
  tests/test_log.py
  tests/test_validator.py
Labels: new feature

#3008 Improve logging for Pg param change
  patroni/postgresql/config.py
  patroni/utils.py
  tests/test_postgresql.py
Labels: enhancement
