Repository patroni/patroni, pull requests merged in 2024-02, with the labels that each got.

#3015 Patroni doesn't filter out some not allowed options from `pg_basebackup`
  patroni/postgresql/bootstrap.py
  tests/test_bootstrap.py
Labels: bug

#2978 Add pending restart reason information
  patroni/api.py
  patroni/ctl.py
  patroni/ha.py
  patroni/postgresql/__init__.py
  patroni/postgresql/bootstrap.py
  patroni/postgresql/config.py
  patroni/utils.py
  tests/__init__.py
  tests/test_api.py
  tests/test_bootstrap.py
  tests/test_ctl.py
  tests/test_postgresql.py
Labels: new feature

#2991 rename citus_handler to mpp_handler
  patroni/api.py
  patroni/ctl.py
  patroni/dcs/__init__.py
  patroni/dcs/consul.py
  patroni/dcs/etcd.py
  patroni/dcs/etcd3.py
  patroni/dcs/kubernetes.py
  patroni/dcs/raft.py
  patroni/dcs/zookeeper.py
  patroni/ha.py
  patroni/postgresql/__init__.py
  patroni/postgresql/bootstrap.py
  patroni/postgresql/config.py
  patroni/postgresql/mpp/__init__.py
  patroni/postgresql/slots.py
  tests/test_api.py
  tests/test_citus.py
  tests/test_ha.py
  tests/test_kubernetes.py
  tests/test_raft.py
  tests/test_zookeeper.py
Labels: refactoring
