Repository patroni/patroni, pull requests merged in 2024-11, with the labels that each got.

#3201 Fixes outdated link to Zalando's tech blog on Patroni
  README.rst
  docs/README.rst
Labels: documentation

#3205 Cache DCS instances to avoid thread leak in `patronictl list -W`
  patroni/ctl.py
  tests/test_ctl.py
Labels: bug

#3207 Make sure only supported parameters are written to connection string
  patroni/postgresql/config.py
  tests/test_postgresql.py
Labels: bug

#3215 Restore compatibility with python-consul2
  patroni/dcs/consul.py
Labels: compatibility

#3217 Compatibility with prettytable>=3.12.0
  patroni/ctl.py
  tests/test_ctl.py
  typings/prettytable/__init__.pyi
Labels: compatibility

#3216 Compatibility with ydiff==1.4.2
  .github/workflows/tests.yaml
  patroni/ctl.py
  requirements.txt
  tests/test_ctl.py
  typings/cdiff/__init__.pyi
  typings/ydiff/__init__.pyi
Labels: compatibility
