Repository patroni/patroni, pull requests merged in 2024-12, with the labels that each got.

#3229 Add optional 'cluster_type' attribute to permanent replication slots.
  docs/dynamic_configuration.rst
  patroni/dcs/__init__.py
Labels: new feature

#3226 Show only the members to be restarted upon restart confirmation
  patroni/ctl.py
Labels: bug

#3223 Implement sync_priority tag
  docs/yaml_configuration.rst
  features/priority_sync.feature
  patroni/config.py
  patroni/config_generator.py
  patroni/ha.py
  patroni/postgresql/sync.py
  patroni/tags.py
  patroni/validator.py
  postgres0.yml
  postgres1.yml
  postgres2.yml
  tests/test_config.py
  tests/test_config_generator.py
  tests/test_ha.py
  tests/test_patroni.py
Labels: new feature

#3232 Cancel long-running jobs on Patroni stop
  patroni/ha.py
  patroni/postgresql/bootstrap.py
Labels: bug

#3233 Compatibility with python-json-logger>=3.1
  .github/workflows/tests.yaml
  patroni/log.py
  patroni/watchdog/base.py
  tests/test_ctl.py
  tests/test_log.py
Labels: compatibility
