Repository patroni/patroni, pull requests merged in 2024-03, with the labels that each got.

#3026 Retry one time on Etcd3 auth error
  patroni/dcs/consul.py
  patroni/dcs/etcd3.py
  patroni/utils.py
  tests/test_consul.py
  tests/test_etcd3.py
Labels: bug

#3016 Refactor Barman scripts and add a sub-command to switch Barman config
  docs/index.rst
  docs/replica_bootstrap.rst
  docs/tools_integration.rst
  patroni/scripts/barman/__init__.py
  patroni/scripts/barman/cli.py
  patroni/scripts/barman/config_switch.py
  patroni/scripts/barman/recover.py
  patroni/scripts/barman/utils.py
  patroni/scripts/barman_recover.py
  setup.py
  tests/test_barman.py
  tests/test_barman_recover.py
Labels: enhancement, refactoring

#2842 Disable WAL streaming on standby node via new boolean tag "nostream"
  docs/dynamic_configuration.rst
  docs/replication_modes.rst
  docs/yaml_configuration.rst
  patroni/config_generator.py
  patroni/dcs/__init__.py
  patroni/ha.py
  patroni/tags.py
  patroni/validator.py
  postgres0.yml
  tests/test_config_generator.py
  tests/test_ha.py
  tests/test_patroni.py
  tests/test_slots.py
  tests/test_validator.py
Labels: new feature

#3038 Set global_config from dynamic_config if DCS data is empty
  patroni/global_config.py
  patroni/ha.py
  tests/test_ha.py
Labels: bug

#3036 Extend behave tests with nostream feature
  features/environment.py
  features/nostream_node.feature
  features/standby_cluster.feature
  features/steps/basic_replication.py
Labels: ci
