Repository patroni/patroni, pull requests merged in 2024-10, with the labels that each got.

#3174 Recheck annotations when reading leader object on 409
  patroni/dcs/kubernetes.py
  tests/test_kubernetes.py
Labels: bug

#3175 Hides the password output in logs when pgaudit is enabled
  patroni/postgresql/bootstrap.py
Labels: enhancement

#3177 Fix docs build
  docs/conf.py
Labels: documentation, compatibility

#3181 Fix issue with mixed setups: primary on pre-v4 and replicas on v4+
  patroni/dcs/__init__.py
Labels: bug

#3180 Partially revert patroni@8c5ab4c
  patroni/postgresql/__init__.py
  patroni/postgresql/config.py
  patroni/postgresql/validator.py
  tests/__init__.py
  tests/test_bootstrap.py
  tests/test_patroni.py
  tests/test_postgresql.py
  tests/test_sync.py
Labels: enhancement

#3186 Temporary pin psycopg2-binary version for macOS
  .github/workflows/install_deps.py
  requirements.dev.txt
  requirements.docs.txt
Labels: ci

#3182 Pyright 1.1.385
  .github/workflows/tests.yaml
  patroni/api.py
  patroni/config.py
  patroni/dcs/__init__.py
  patroni/dcs/etcd3.py
  patroni/dcs/exhibitor.py
  patroni/dcs/kubernetes.py
  patroni/dcs/raft.py
  patroni/dcs/zookeeper.py
  patroni/global_config.py
  patroni/log.py
  patroni/postgresql/bootstrap.py
  patroni/postgresql/cancellable.py
  patroni/postgresql/mpp/citus.py
  patroni/utils.py
  patroni/validator.py
Labels: codestyle

#3185 Add documentation for sslnegotiation option
  docs/ENVIRONMENT.rst
  docs/yaml_configuration.rst
Labels: documentation

#3191 Switch to py-consul
  README.rst
  docs/installation.rst
  patroni/dcs/consul.py
  requirements.txt
  setup.py
  tests/test_consul.py
  typings/consul/__init__.pyi
  typings/consul/base.pyi
  typings/consul/check.pyi
Labels: compatibility

#3198 Run on_role_change cb after a failed primary recovery
  features/recovery.feature
  features/steps/recovery.py
  patroni/ha.py
  tests/test_ha.py
Labels: enhancement
