Repository patroni/patroni, pull requests merged in 2024-07, with the labels that each got.

#3095 Use trusted publishers for pypi
  .github/workflows/release.yaml
Labels: ci

#3094 Fix plain Postgres synchronous replication mode
  patroni/ha.py
  patroni/postgresql/config.py
  tests/test_ha.py
Labels: bug

#3092 make postgresql.parameter more clarity
  docs/dynamic_configuration.rst
  docs/yaml_configuration.rst
Labels: documentation

#3097 Handle logical slots invalidation on a standby
  patroni/postgresql/slots.py
  tests/test_slots.py
Labels: bug

#3098 Fix race condition with logical slot advance and copy
  patroni/postgresql/slots.py
  tests/test_slots.py
Labels: bug

#3103 Finish refactoring of the Status class
  patroni/api.py
  patroni/dcs/__init__.py
  patroni/ha.py
  patroni/utils.py
  tests/test_api.py
  tests/test_slots.py
  tests/test_zookeeper.py
Labels: bug, refactoring

#3105 Get rid of SLOT_ADVANCE_AVAILABLE_VERSION in `dcs/__init__.py`
  patroni/dcs/__init__.py
  patroni/postgresql/__init__.py
Labels: refactoring

#3100 Advance permanent slots for cascading nodes while in failsafe
  features/dcs_failsafe_mode.feature
  patroni/api.py
  patroni/dcs/__init__.py
  patroni/ha.py
  tests/__init__.py
  tests/test_ha.py
Labels: bug

#3107 Refactor update_leader() method
  patroni/dcs/__init__.py
  patroni/dcs/kubernetes.py
  patroni/ha.py
  tests/test_consul.py
  tests/test_etcd.py
  tests/test_etcd3.py
  tests/test_kubernetes.py
  tests/test_raft.py
  tests/test_zookeeper.py
Labels: refactoring, codestyle

#3109 Patroni doesn't forece wal_log_hints anymore
  docs/patroni_configuration.rst
Labels: documentation

#3112 Don't let the current node be chosen as synchronous
  patroni/ha.py
  patroni/postgresql/sync.py
  tests/test_sync.py
Labels: bug

#3113 Ignore restapi.allowlist_include_members for POST /failsafe
  patroni/api.py
Labels: bug
