Repository patroni/patroni, pull requests merged in 2024-05, with the labels that each got.

#3058 Compatibility with python 3.12
  .github/workflows/install_deps.py
  .github/workflows/release.yaml
  .github/workflows/run_tests.py
  .github/workflows/tests.yaml
  patroni/log.py
  tests/test_ha.py
Labels: ci, compatibility

#3057 Add date to every released version
  docs/releases.rst
Labels: documentation

#3024 Instruct etcd to delete old revisions
  docker/entrypoint.sh
Labels: enhancement

#3063 Make wal_log_hints configurable
  docs/dynamic_configuration.rst
  docs/ha_multi_dc.rst
  docs/replication_modes.rst
  docs/standby_cluster.rst
  docs/yaml_configuration.rst
  patroni/config.py
  patroni/config_generator.py
  patroni/postgresql/config.py
  tests/test_config_generator.py
Labels: enhancement
