Repository patroni/patroni, pull requests merged in 2024-04, with the labels that each got.

#3018 Use importlib_resources to read validators file
  patroni/postgresql/available_parameters/__init__.py
  patroni/postgresql/validator.py
  tests/test_postgresql.py
Labels: bug

#3040 Use `target_session_attrs` only when multiple hosts in standby_cluster
  docs/index.rst
  docs/replica_bootstrap.rst
  docs/standby_cluster.rst
  patroni/postgresql/config.py
  patroni/postgresql/rewind.py
  tests/test_postgresql.py
  tests/test_rewind.py
Labels: enhancement, documentation

#3042 Compatibility with ydiff>=1.3
  patroni/ctl.py
Labels: bug

#3046 Fix readthedocs builds
  docs/conf.py
  requirements.docs.txt
  tox.ini
Labels: documentation

#3047 Update contributing link
  README.rst
Labels: documentation
