Repository patroni/patroni, pull requests merged in 2024-08, with the labels that each got.

#3120 Compatibility with v17 beta3
  patroni/postgresql/available_parameters/0_postgres.yml
Labels: compatibility

#3119 Use get_parameter_status() method instead of info.parameter_status()
  patroni/config_generator.py
  patroni/psycopg.py
  tests/__init__.py
  tests/test_config_generator.py
Labels: compatibility

#3122 Implement support of `log.mode`.
  docs/ENVIRONMENT.rst
  docs/yaml_configuration.rst
  patroni/config.py
  patroni/file_perm.py
  patroni/log.py
  patroni/validator.py
  tests/test_config.py
  tests/test_file_perm.py
  tests/test_log.py
Labels: new feature

#2668 Quorum based failover
  docs/citus.rst
  docs/dynamic_configuration.rst
  docs/replication_modes.rst
  docs/rest_api.rst
  features/quorum_commit.feature
  features/steps/quorum_commit.py
  patroni/api.py
  patroni/config.py
  patroni/dcs/__init__.py
  patroni/dcs/kubernetes.py
  patroni/global_config.py
  patroni/ha.py
  patroni/postgresql/__init__.py
  patroni/postgresql/sync.py
  patroni/quorum.py
  patroni/utils.py
  tests/test_api.py
  tests/test_etcd.py
  tests/test_ha.py
  tests/test_kubernetes.py
  tests/test_quorum.py
  tests/test_raft.py
  tests/test_sync.py
Labels: help wanted, new feature

#2755 Register Citus secondaries in pg_dist_node
  features/citus.feature
  patroni/postgresql/mpp/citus.py
  tests/__init__.py
  tests/test_citus.py
Labels: enhancement, new feature

#3124 Add synchronous_node_count to dynamic conf doc
  docs/dynamic_configuration.rst
Labels: documentation

#2894 Remove user creation
  patroni/config.py
  patroni/postgresql/bootstrap.py
  tests/test_ha.py
Labels: deprecation

#3128 Fix timestamp order in postmaster check log
  patroni/postgresql/postmaster.py
Labels: bug

#3126 Fix request URL in failsafe handling log
  patroni/dcs/__init__.py
  patroni/ha.py
  patroni/request.py
  tests/test_ha.py
Labels: bug

#3129 Remove patronictl failover --leader option
  docs/patronictl.rst
  patroni/ctl.py
  tests/test_ctl.py
Labels: deprecation

#3130 Remove postgres --describe-config validation
  patroni/postgresql/__init__.py
  patroni/postgresql/available_parameters/0_postgres.yml
  patroni/postgresql/config.py
  patroni/postgresql/misc.py
  patroni/postgresql/validator.py
  patroni/utils.py
  tests/__init__.py
  tests/test_bootstrap.py
  tests/test_patroni.py
  tests/test_postgresql.py
  tests/test_sync.py
  tests/test_utils.py
Labels: bug

#3137 Follow up on #2755
  Dockerfile.citus
  docker/README.md
  docs/citus.rst
  kubernetes/README.md
  patroni/postgresql/mpp/citus.py
Labels: enhancement, documentation

#3139 Add line with localhost to pgpass when unix sockets are detected
  patroni/postgresql/config.py
  tests/test_postgresql.py
Labels: bug

#3138 Added a new flag to ignore unsuccessful bind
  docs/patroni_configuration.rst
  patroni/__main__.py
  patroni/validator.py
  tests/test_validator.py
Labels: enhancement
