Repository patroni/patroni, pull requests merged in 2025-10, with the labels that each got.

#3454 Fix issue with renaming leader node in sync mode and pause
  patroni/ha.py
  tests/test_ha.py
Labels: bug

#3458 Fix typo in docs/installation.rst
  docs/installation.rst
  features/permanent_slots.feature
Labels: ci, documentation

#3457 Trigger pg_rewind check when the same primary increased timeline
  patroni/ha.py
  tests/test_ha.py
Labels: bug

#3450 Add support for notify-reload systemd unit type
  patroni/daemon.py
Labels: new feature

#3460 Introduce Jepsen tests
  .github/workflows/jepsen.yaml
  jepsen/Dockerfile
  jepsen/docker-compose.yml
  jepsen/jepsen/project.clj
  jepsen/jepsen/run.sh
  jepsen/jepsen/src/jepsen/patroni.clj
  jepsen/jepsen/test/jepsen/patroni_test.clj
  jepsen/runit/etcd/run
  jepsen/runit/patroni/run
Labels: ci
