Repository patroni/patroni, pull requests merged in 2025-05, with the labels that each got.

#3338 Properly handle Unavailable exception raised by Etcd v3
  patroni/dcs/etcd3.py
  tests/test_etcd3.py
Labels: bug

#3352 Make sure str representation is used for click options
  patroni/ctl.py
  tests/test_ctl.py
Labels: bug

#3341 Make sure we refresh Etcd v3 lease at least once per HA loop
  patroni/dcs/etcd3.py
Labels: bug

#3354 Change min click version to 5.0
  requirements.txt
Labels: compatibility

#3316 Provide receive and replay LSN/lag information in API and ctl
  docker/README.md
  docs/citus.rst
  docs/patronictl.rst
  docs/rest_api.rst
  kubernetes/README.md
  patroni/ctl.py
  patroni/dcs/__init__.py
  patroni/ha.py
  patroni/postgresql/__init__.py
  patroni/postgresql/rewind.py
  patroni/utils.py
  tests/test_ctl.py
  tests/test_ha.py
  tests/test_postgresql.py
  typings/prettytable/__init__.pyi
Labels: new feature

#3355 Increase stability of the callback_executor test
  tests/test_callback_executor.py
Labels: ci

#3348 Recheck annotations when doing attempt_to_acquire_leader on 409
  patroni/dcs/kubernetes.py
  tests/test_kubernetes.py
Labels: bug

#3356 Consider replay_lsn when advancing slots
  patroni/postgresql/slots.py
  tests/test_slots.py
Labels: bug

#3324 Update patroni_configuration.rst
  docs/patroni_configuration.rst
Labels: documentation

#3357 Properly report unknown receive lsn/lag
  patroni/ha.py
  patroni/utils.py
Labels: bug

#3362 Make unit tests pass with click==8.2.1
  tests/test_ctl.py
Labels: ci, compatibility
