Repository patroni/patroni, pull requests merged in 2025-03, with the labels that each got.

#3301 Add support for systemd "notify" unit type
  README.rst
  docs/installation.rst
  extras/startup-scripts/patroni.service
  patroni/daemon.py
  setup.py
Labels: new feature

#3293 Convert states to enums
  patroni/api.py
  patroni/ctl.py
  patroni/dcs/__init__.py
  patroni/dcs/consul.py
  patroni/dcs/kubernetes.py
  patroni/ha.py
  patroni/postgresql/__init__.py
  patroni/postgresql/bootstrap.py
  patroni/postgresql/config.py
  patroni/postgresql/misc.py
  patroni/postgresql/mpp/citus.py
  patroni/postgresql/sync.py
  patroni/utils.py
  tests/__init__.py
  tests/test_api.py
  tests/test_bootstrap.py
  tests/test_consul.py
  tests/test_ctl.py
  tests/test_ha.py
  tests/test_kubernetes.py
  tests/test_patroni.py
  tests/test_postgresql.py
  tests/test_slots.py
Labels: codestyle

#3309 Move initialization of global_config to Patroni class
  patroni/__main__.py
  patroni/ha.py
  patroni/postgresql/__init__.py
Labels: bug

#3308 Fix permissions of out-of-PGDATA created postgresql.conf
  patroni/postgresql/config.py
Labels: enhancement
