Repository patroni/patroni, pull requests merged in 2025-04, with the labels that each got.

#3336 Limit py-consul version depending on python version
  .github/workflows/install_deps.py
  requirements.txt
Labels: compatibility

#3303 Convert roles to enums
  patroni/__main__.py
  patroni/api.py
  patroni/ctl.py
  patroni/dcs/__init__.py
  patroni/dcs/consul.py
  patroni/dcs/kubernetes.py
  patroni/ha.py
  patroni/postgresql/__init__.py
  patroni/postgresql/config.py
  patroni/postgresql/misc.py
  patroni/postgresql/mpp/citus.py
  patroni/postgresql/rewind.py
  patroni/postgresql/slots.py
  tests/test_api.py
  tests/test_callback_executor.py
  tests/test_consul.py
  tests/test_ctl.py
  tests/test_ha.py
  tests/test_kubernetes.py
  tests/test_patroni.py
  tests/test_postgresql.py
  tests/test_slots.py
Labels: codestyle

#3318 Ignore stale Etcd nodes by comparing cluster term
  patroni/dcs/etcd.py
  patroni/dcs/etcd3.py
  tests/test_etcd.py
Labels: bug
