Repository patroni/patroni, pull requests merged in 2025-02, with the labels that each got.

#3265 Temp revert of "Enable behave tests with Citus 13 and PostgreSQL 17"
  .github/workflows/install_deps.py
Labels: ci

#3267 Handle all exceptions raised by subprocess in controldata() method
  patroni/postgresql/__init__.py
Labels: bug

#3269 Improve replication_state=streaming check in behave
  features/standby_cluster.feature
  features/steps/patroni_api.py
Labels: ci

#3245 Don't touch logical failover slots
  features/dcs_failsafe_mode.feature
  features/environment.py
  features/ignored_slots.feature
  features/nostream_node.feature
  features/permanent_slots.feature
  features/standby_cluster.feature
  features/steps/slots.py
  patroni/postgresql/__init__.py
  patroni/postgresql/slots.py
Labels: enhancement

#3277 Cleanup after unit tests
  tests/__init__.py
Labels: ci

#3268 Take advantage of written_lsn and latest_end_lsn from pg_stat_wal_receiver
  patroni/api.py
  patroni/postgresql/__init__.py
  tests/__init__.py
  tests/test_api.py
  tests/test_slots.py
Labels: enhancement

#3257 Implement kubernetes.bootstrap_labels
  docs/ENVIRONMENT.rst
  docs/yaml_configuration.rst
  features/backup_create.py
  features/backup_restore.py
  features/bootstrap_labels.feature
  features/environment.py
  features/steps/bootstrap_labels.py
  patroni/api.py
  patroni/config.py
  patroni/ctl.py
  patroni/dcs/kubernetes.py
  patroni/postgresql/__init__.py
  patroni/utils.py
  patroni/validator.py
  tests/test_kubernetes.py
  tests/test_validator.py
Labels: new feature

#3283 Bump pyright to 1.1.394
  .github/workflows/tests.yaml
  patroni/api.py
  patroni/config_generator.py
  patroni/dcs/etcd.py
  patroni/postgresql/config.py
  patroni/validator.py
  pyrightconfig.json
  tests/test_config_generator.py
Labels: codestyle, compatibility

#3278 Fix a couple of bugs in quorum state machine
  patroni/ha.py
  patroni/quorum.py
  tests/test_quorum.py
Labels: bug

#3285 Re-apply "Enable behave tests with Citus 13 and PostgreSQL 17"
  .github/workflows/install_deps.py
Labels: ci, citus

#3287 Compatibility with python 3.6
  tests/test_consul.py
  tests/test_kubernetes.py
Labels: ci, compatibility

#3297 Fix bug with priority failover
  patroni/ha.py
  tests/test_api.py
  tests/test_ha.py
Labels: bug

#3299 Update config files on SIGHUP
  patroni/postgresql/config.py
Labels: enhancement

#3296 Implement --print option for --validate-config
  docs/patroni_configuration.rst
  patroni/__main__.py
  tests/test_patroni.py
Labels: enhancement
