Repository patroni/patroni, pull requests merged in 2025-01, with the labels that each got.

#3238 Improve error on empty or non dict config file
  patroni/config.py
  tests/test_config.py
Labels: enhancement

#3246 Compatibility with python 3.13
  .github/workflows/tests.yaml
  setup.py
  tests/test_consul.py
  tests/test_kubernetes.py
  tox.ini
Labels: compatibility

#3244 Avoid dropping physical slots too early
  patroni/postgresql/slots.py
  tests/test_slots.py
Labels: bug

#3256 Fall back to default iter_modules if pyinstaller toc is not present.
  patroni/dynamic_loader.py
Labels: compatibility

#3262 Enable behave tests with Citus 13 and PostgreSQL 17
  .github/workflows/install_deps.py
  .github/workflows/run_tests.py
Labels: ci

#3263 Fix race condition in priority sync behave tests
  features/priority_sync.feature
Labels: ci

#3260 Fix a few little issues with 9.5 support
  patroni/postgresql/rewind.py
  patroni/postgresql/sync.py
  tests/test_rewind.py
  tests/test_sync.py
Labels: bug
