Repository patroni/patroni, pull requests merged in 2025-07, with the labels that each got.

#3394 Compatibility with PostgreSQL 18 beta1
  patroni/postgresql/available_parameters/0_postgres.yml
  patroni/postgresql/postmaster.py
Labels: compatibility

#3364 Multi citus support
  patroni/__main__.py
  patroni/config.py
  patroni/postgresql/mpp/__init__.py
  patroni/postgresql/mpp/citus.py
  patroni/validator.py
  tests/test_citus.py
Labels: new feature

#3361 Clean cluster demotion
  features/environment.py
  features/standby_cluster.feature
  features/steps/standby_cluster.py
  patroni/ha.py
  patroni/postgresql/__init__.py
  patroni/postgresql/rewind.py
  tests/test_ha.py
  tests/test_postgresql.py
  tests/test_rewind.py
Labels: enhancement

#3402 docs: improve planning section with 2-node cluster guidance
  docs/README.rst
Labels: documentation

#3404 Failsafe mode wasn't always triggered in case of Etcd unavailability
  patroni/dcs/etcd.py
  tests/test_etcd.py
Labels: bug
